services:
  - type: web
    name: suivi-evaluation-projets
    env: python
    buildCommand: pip install -r requirements.txt && python database_init.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
